from ROOT import *
import os
import sys
import math
from time import strftime

Name='_Muon_newQCD'

here= os.popen('pwd').readlines()[0].replace('\n','')
submitter = open('submit.csh','w')

submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -r MuonPtLLRescales.csv -f CentralValues"+Name+"\n"
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J CentralValues -q 1nh < submit.csh")
os.system("sleep 5")
exit()
submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -pd -r MuonPtLLRescales.csv -f PUDownValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J PUDownValues -q 1nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -pd -r MuonPtLLRescales.csv -f PUUpValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J PUUpValues -q 1nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__MuScaleDown_2014_08_03_17_36_35/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__MuScaleDown_2014_10_31_05_03_17/SummaryFiles -r MuonPtLLRescales.csv -f MuDownValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J MuDownValues -q 1nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__MuScaleUp_2014_08_03_06_53_40/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__MuScaleUp_2014_10_31_02_29_45/SummaryFiles -r MuonPtLLRescales.csv -f MuUpValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J MuUpValues -q 1nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__JetScaleUp_2014_08_01_22_07_07/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__MuSmear_2014_10_31_11_40_46/SummaryFiles -r MuonPtLLRescales.csv -f MuSmearValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J MuSmearValues -q 1nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__JetScaleDown_2014_08_02_20_11_32/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__JetScaleDown_2014_10_31_00_21_07/SummaryFiles  -r MuonPtLLRescales.csv -f JetDownValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J JetDownValues -q 1nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__JetScaleUp_2014_08_01_22_07_07/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__JetScaleUp_2014_10_30_20_01_59/SummaryFiles -r MuonPtLLRescales.csv -f JetUpValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J JetUpValues -q 1nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__JetSmear_2014_08_04_05_17_00/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__JetSmear_2014_10_31_09_02_06/SummaryFiles -r MuonPtLLRescales.csv -f JetSmearValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J JetSmearValues -q 1nh < submit.csh")
os.system("sleep 5")

#submitter = open('submit.csh','w')
#submitter.write('#!/bin/csh\n')
#submitter.write('cd '+here+'\n')
#submitter.write('eval `scramv1 runtime -csh`\n\n')
#submitter.write('cd -\n')
#submitter.write('cp '+here +'/CMSStyle.py .\n')
#submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
#submitter.write('cp '+here +'/HistoCreation.py .\n')
#submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
#submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
#String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_MCShapeMuons_2014_08_08_02_14_04/SummaryFiles/ZJetsJBin_matchingdown.root -r MuonPtLLRescales.csv -f ZMatchDownValues"+Name+'\n'
#submitter.write(String)
#submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
#submitter.close()
#os.system("bsub -J ZMatchDownValues -q 1nh < submit.csh")
#os.system("sleep 5")

#submitter = open('submit.csh','w')
#submitter.write('#!/bin/csh\n')
#submitter.write('cd '+here+'\n')
#submitter.write('eval `scramv1 runtime -csh`\n\n')
#submitter.write('cd -\n')
#submitter.write('cp '+here +'/CMSStyle.py .\n')
#submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
#submitter.write('cp '+here +'/HistoCreation.py .\n')
#submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
#submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
#String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_MCShapeMuons_2014_08_08_02_14_04/SummaryFiles/ZJetsJBin_matchingup.root -r MuonPtLLRescales.csv -f ZMatchUpValues"+Name+'\n'
#submitter.write(String)
#submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
#submitter.close()
#os.system("bsub -J ZMatchUpValues -q 1nh < submit.csh")
#os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_FastSimZMuons_2014_09_08_16_41_39/SummaryFiles/ZJetsJBin_scaledown.root -r MuonPtLLRescales.csv -f ZScaleDownValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J ZScaleDownValues -q 1nh < submit.csh")
os.system("sleep 5")


submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/MuonPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_mumu2012_NonEmulatedTriggers.py .\n')
String = "python MakePlotsSingle_mumu2012_NonEmulatedTriggers.py -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_FastSimZMuons_2014_09_08_16_41_39/SummaryFiles/ZJetsJBin_scaleup.root -r MuonPtLLRescales.csv -f ZScaleUpValues"+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J ZScaleUpValues -q 1nh < submit.csh")
