from ROOT import *
import os
import sys
import math
from time import strftime

Name='_Electrons'

here= os.popen('pwd').readlines()[0].replace('\n','')
submitter = open('submit.csh','w')

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -r ElectronPtLLRescales.csv -f CentralValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J CentralValues -q 8nh < submit.csh")
os.system("sleep 5")

exit()
submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -pd -r ElectronPtLLRescales.csv -f PUDownValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J PUDownValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -pd -r ElectronPtLLRescales.csv -f PUUpValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J PUUpValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_Mar10_EleSystsFromEGM13001_Systematics__EleScaleDown_2015_03_15_15_53_17/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_Mar10_EleSystsFromEGM13001_Systematics__EleScaleDown_2015_03_15_15_53_17/SummaryFiles -r ElectronPtLLRescales.csv -f EleDownValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J EleDownValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_Mar10_EleSystsFromEGM13001_Systematics__EleScaleUp_2015_03_14_19_43_31/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_Mar10_EleSystsFromEGM13001_Systematics__EleScaleUp_2015_03_14_19_43_31/SummaryFiles -r ElectronPtLLRescales.csv -f EleUpValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J EleUpValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_Mar10_EleSystsFromEGM13001_Systematics__EleSmear_2015_03_16_08_35_35/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_Mar10_EleSystsFromEGM13001_Systematics__EleSmear_2015_03_16_08_35_35/SummaryFiles -r ElectronPtLLRescales.csv -f EleSmearValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J EleSmearValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_June26_Systematics__JetScaleDown_2014_06_29_00_15_08/SummaryFiles/ /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_Oct29FixedGenMassesStatusOne_Systematics__JetScaleDown_2014_11_01_16_10_00/SummaryFiles/ -r ElectronPtLLRescales.csv -f JetDownValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J JetDownValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_June26_Systematics__JetScaleUp_2014_06_27_18_22_36/SummaryFiles  /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_Oct29FixedGenMassesStatusOne_Systematics__JetScaleUp_2014_10_30_20_01_04/SummaryFiles  -r ElectronPtLLRescales.csv -f JetUpValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J JetUpValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_June26_Systematics__JetSmear_2014_06_29_17_51_55/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_Oct29FixedGenMassesStatusOne_Systematics__JetSmear_2014_10_30_13_45_57/SummaryFiles/ -r ElectronPtLLRescales.csv -f JetSmearValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J JetSmear -q 8nh < submit.csh")
os.system("sleep 5")


#submitter = open('submit.csh','w')
#submitter.write('#!/bin/csh\n')
#submitter.write('cd '+here+'\n')
#submitter.write('eval `scramv1 runtime -csh`\n\n')
#submitter.write('cd -\n')
#submitter.write('cp '+here +'/CMSStyle.py .\n')
#submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
#submitter.write('cp '+here +'/HistoCreation.py .\n')
#submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
#submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
#String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_MCShapeElectrons_2014_08_08_13_02_05/SummaryFiles/ZJetsJBin_matchingdown.root -r ElectronPtLLRescales.csv -f ZMatchDownValues'+Name+'\n'
#submitter.write(String)
#submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
#submitter.close()
#os.system("bsub -J ZMatchDownValues -q 8nh < submit.csh")


#submitter = open('submit.csh','w')
#submitter.write('#!/bin/csh\n')
#submitter.write('cd '+here+'\n')
#submitter.write('eval `scramv1 runtime -csh`\n\n')
#submitter.write('cd -\n')
#submitter.write('cp '+here +'/CMSStyle.py .\n')
#submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
#submitter.write('cp '+here +'/HistoCreation.py .\n')
#submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
#submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
#String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_MCShapeElectrons_2014_08_08_13_02_05/SummaryFiles/ZJetsJBin_matchingup.root -r ElectronPtLLRescales.csv -f ZMatchUpValues'+Name+'\n'
#submitter.write(String)
#submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
#submitter.close()
#os.system("bsub -J ZMatchUpValues -q 8nh < submit.csh")


submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_FastSimZElectrons_2014_09_05_15_20_20/SummaryFiles/ZJetsJBin_scaledown.root -r ElectronPtLLRescales.csv -f ZScaleDownValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J ZScaleDownValues -q 8nh < submit.csh")
os.system("sleep 5")


submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/CMS_lumi.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_ee_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/ElectronPtLLRescales.csv .\n')
submitter.write('cp '+here +'/MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py .\n')
String = 'python MakePlotsSingle_ee2012_NewQCD_NonEmulatedTriggers.py  -I -i Selection_ee_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_ElectronStrict_FastSimZElectrons_2014_09_05_15_20_20/SummaryFiles/ZJetsJBin_scaleup.root -r ElectronPtLLRescales.csv -f ZScaleUpValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelElectronIntegrals_Rescaled\n')
submitter.close()
os.system("bsub -J ZScaleUpValues -q 8nh < submit.csh")
os.system("sleep 5")

