from ROOT import *
import os
import sys
import math
from time import strftime

Name='_Muons'

here= os.popen('pwd').readlines()[0].replace('\n','')
submitter = open('submit.csh','w')

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -f CentralValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J CentralValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -pd -f PUDownValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J PUDownValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -pd -f PUUpValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J PUUpValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__MuScaleDown_2014_08_03_17_36_35/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__MuScaleDown_2014_10_31_05_03_17/SummaryFiles -f EleDownValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J EleDownValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__MuScaleUp_2014_08_03_06_53_40/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__MuScaleUp_2014_10_31_02_29_45/SummaryFiles -f EleUpValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J EleUpValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__JetScaleUp_2014_08_01_22_07_07/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__MuSmear_2014_10_31_11_40_46/SummaryFiles -f EleSmearValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J EleSmearValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__JetScaleDown_2014_08_02_20_11_32/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__JetScaleDown_2014_10_31_00_21_07/SummaryFiles -f JetDownValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J JetDownValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__JetScaleUp_2014_08_01_22_07_07/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__JetScaleUp_2014_10_30_20_01_59/SummaryFiles -f JetUpValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J JetUpValues -q 8nh < submit.csh")
os.system("sleep 5")

submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -e /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_July31_Systematics__JetSmear_2014_08_04_05_17_00/SummaryFiles /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_Oct30_FixedGenMassesStatusOne_Systematics__JetSmear_2014_10_31_09_02_06/SummaryFiles -f JetSmearValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J JetSmear -q 8nh < submit.csh")
os.system("sleep 5")


#submitter = open('submit.csh','w')
#submitter.write('#!/bin/csh\n')
#submitter.write('cd '+here+'\n')
#submitter.write('eval `scramv1 runtime -csh`\n\n')
#submitter.write('cd -\n')
#submitter.write('cp '+here +'/CMSStyle.py .\n')
#submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
#submitter.write('cp '+here +'/HistoCreation.py .\n')
#submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
#submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
#String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_MCShapeMuons_2014_08_08_13_02_05/SummaryFiles/ZJetsJBin_matchingdown.root -f ZMatchDownValues'+Name+'\n'
#submitter.write(String)
#submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
#submitter.close()
#os.system("bsub -J ZMatchDownValues -q 8nh < submit.csh")


#submitter = open('submit.csh','w')
#submitter.write('#!/bin/csh\n')
#submitter.write('cd '+here+'\n')
#submitter.write('eval `scramv1 runtime -csh`\n\n')
#submitter.write('cd -\n')
#submitter.write('cp '+here +'/CMSStyle.py .\n')
#submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
#submitter.write('cp '+here +'/HistoCreation.py .\n')
#submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
#submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
#String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_MCShapeMuons_2014_08_08_13_02_05/SummaryFiles/ZJetsJBin_matchingup.root -f ZMatchUpValues'+Name+'\n'
#submitter.write(String)
#submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
#submitter.close()
#os.system("bsub -J ZMatchUpValues -q 8nh < submit.csh")


submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_FastSimZMuons_2014_09_05_15_20_20/SummaryFiles/ZJetsJBin_scaledown.root -f ZScaleDownValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J ZScaleDownValues -q 8nh < submit.csh")
os.system("sleep 5")


submitter = open('submit.csh','w')
submitter.write('#!/bin/csh\n')
submitter.write('cd '+here+'\n')
submitter.write('eval `scramv1 runtime -csh`\n\n')
submitter.write('cd -\n')
submitter.write('cp '+here +'/CMSStyle.py .\n')
submitter.write('cp '+here +'/WeightsAndFilters.py .\n')
submitter.write('cp '+here +'/HistoCreation.py .\n')
submitter.write('cp '+here +'/Selection_mumu_NewQCDStudy_125jetptcut.csv .\n')
submitter.write('cp '+here +'/FiducialCutsMuon.py .\n')
String = 'python FiducialCutsMuon.py  -I -i Selection_mumu_NewQCDStudy_125jetptcut.csv -s /store/user/dnash/LQAnalyzerOutput2/NTupleAnalyzer_V00_02_06_David_2012_MuonStrict_FastSimZMuons_2014_09_05_15_20_20/SummaryFiles/ZJetsJBin_scaleup.root -f ZScaleUpValues'+Name+'\n'
submitter.write(String)
submitter.write('cp *.txt '+here+'/ParallelMuonIntegralsFiducial200Cut\n')
submitter.close()
os.system("bsub -J ZScaleUpValues -q 8nh < submit.csh")
os.system("sleep 5")
